export const tokens = {
  colors: {
    bg: 'var(--color-bg)',
    bgSecondary: 'var(--color-bg-secondary)',
    bgTertiary: 'var(--color-bg-tertiary)',
    bgElevated: 'var(--color-bg-elevated)',
    fg: 'var(--color-fg)',
    fgMuted: 'var(--color-fg-muted)',
    fgSubtle: 'var(--color-fg-subtle)',
    primary: 'var(--color-primary)',
    primaryHover: 'var(--color-primary-hover)',
    primaryFg: 'var(--color-primary-fg)',
    destructive: 'var(--color-destructive)',
    destructiveHover: 'var(--color-destructive-hover)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    info: 'var(--color-info)',
    border: 'var(--color-border)',
    borderHover: 'var(--color-border-hover)',
    inputBg: 'var(--color-input-bg)',
    ring: 'var(--color-ring)',
    overlay: 'var(--color-overlay)',
  },
  spacing: {
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    20: 'var(--space-20)',
    24: 'var(--space-24)',
  },
  fontSize: {
    11: 'var(--text-11)',
    12: 'var(--text-12)',
    13: 'var(--text-13)',
    14: 'var(--text-14)',
    16: 'var(--text-16)',
    18: 'var(--text-18)',
    20: 'var(--text-20)',
    24: 'var(--text-24)',
    30: 'var(--text-30)',
    36: 'var(--text-36)',
    48: 'var(--text-48)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    full: 'var(--radius-full)',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    focus: 'var(--shadow-focus)',
  },
  zIndex: {
    dropdown: 'var(--z-dropdown)',
    overlay: 'var(--z-overlay)',
    modal: 'var(--z-modal)',
    toast: 'var(--z-toast)',
  },
} as const
